{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "vals-operator.fullname" . }}
  labels:
    {{- include "vals-operator.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: "metrics"
    path: "/metrics"
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vals-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}