# permissions for end users to edit dbsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dbsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vals-operator
    app.kubernetes.io/part-of: vals-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbsecret-editor-role
rules:
- apiGroups:
  - digitalis.io
  resources:
  - dbsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - digitalis.io
  resources:
  - dbsecrets/status
  verbs:
  - get
