# permissions for end users to view dbsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dbsecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vals-operator
    app.kubernetes.io/part-of: vals-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbsecret-viewer-role
rules:
- apiGroups:
  - digitalis.io
  resources:
  - dbsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - digitalis.io
  resources:
  - dbsecrets/status
  verbs:
  - get
