---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - digitalis.io
  resources:
  - dbsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - digitalis.io
  resources:
  - dbsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - digitalis.io
  resources:
  - dbsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - digitalis.io
  resources:
  - valssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - digitalis.io
  resources:
  - valssecrets/finalizers
  verbs:
  - update
- apiGroups:
  - digitalis.io
  resources:
  - valssecrets/status
  verbs:
  - get
  - patch
  - update
